# Generated by Django 2.2.2 on 2019-06-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount_of_probes', models.IntegerField(max_length=1000)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
    ]
