# Generated by Django 2.2.2 on 2019-06-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(db_index=True, default='null_entry', max_length=150),
        ),
        migrations.AlterField(
            model_name='report',
            name='amount_of_probes',
            field=models.IntegerField(),
        ),
    ]
