# Generated by Django 2.2.2 on 2019-06-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20190629_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='mean',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='report',
            name='median',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AlterField(
            model_name='report',
            name='amount_of_probes',
            field=models.PositiveIntegerField(),
        ),
    ]
