# Generated by Django 2.2.2 on 2019-07-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20190702_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.CharField(default='Your note', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='place',
            field=models.CharField(default='Altay Kray, Salt lake', max_length=50),
        ),
    ]
